---
# - name: Setup Network VM
#   hosts: networkpve
#   become: true
#   # gather_facts: true

#   roles:
#     - basics
#     # - install_docker
    
- name: Setup Network VM
  hosts: networkpve
  become: true
  gather_facts: false

  roles: 
    # - install_portainer
    - install_wireguard
    # - install_pihole

